apiVersion: v1
kind: PersistentVolume                    # 1
metadata:
  name: mysql-pv
spec:
  capacity:                               # 2
    storage: 2Gi
  volumeMode: Filesystem                  # 3
  accessModes:                            # 4
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain   # 5
  hostPath:                               # 6
    path: /data/mysql
