apiVersion: v1
kind: PersistentVolumeClaim   # 1
metadata:
  name: mysql-pv-claim
spec:
  accessModes:                # 2
    - ReadWriteOnce
  resources:                  # 3
    requests:
      storage: 1Gi
  storageClassName: ""        # 4
